function list = supportedcontrols(),

	list = {...
		'BalancethicknessThickeningRate',...
		'FrictionCoefficient',...
		'FrictionAs',...
		'MaterialsRheologyBbar',...
		'DamageDbar',...
		'Vx',...
		'Vy',...
		'Thickness',...
		'BalancethicknessOmega',...
		'BalancethicknessApparentMassbalance',...
		'MaterialsRheologyB'};
